name: ✨ Feature Request
description: Suggest a new feature or enhancement for swift-build action
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe your idea clearly and provide context.

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: What feature would you like to see added?
      placeholder: A clear and concise description of what you want to happen
    validations:
      required: true

  - type: textarea
    id: problem-statement
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: Describe the current limitation or pain point this feature would address
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work?
      placeholder: |
        Example configuration or behavior:
        
        ```yaml
        - uses: brightdigit/swift-build@v1.3.0
          with:
            new-parameter: value
        ```
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other solutions have you considered?
      placeholder: Describe any alternative solutions or workarounds you've considered

  - type: dropdown
    id: platform-scope
    attributes:
      label: Platform Scope
      description: Which platforms would this feature affect?
      multiple: true
      options:
        - All platforms
        - Ubuntu/Linux only
        - macOS only
        - iOS
        - watchOS
        - tvOS
        - visionOS

  - type: checkboxes
    id: feature-checklist
    attributes:
      label: Feature Checklist
      options:
        - label: This feature would be useful for other users
        - label: This feature maintains backward compatibility
        - label: I would be willing to help implement this feature