name: Swift Package Tests

on:
  push

jobs:
  test-single-target-macos:
    name: Test Single Target Package (macOS)
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        include:
          # SPM Build Matrix
          - runs-on: macos-15
            xcode: "/Applications/Xcode_16.4.app"
            use-xcbeautify: "true"

          # SPM Build-Only Matrix
          - runs-on: macos-15
            xcode: "/Applications/Xcode_16.4.app"
            use-xcbeautify: "true"
            build-only: "true"

          # macOS Build Matrix
          - type: macos
            runs-on: macos-15
            xcode: "/Applications/Xcode_16.4.app"
            use-xcbeautify: "true"

          # macOS Build-Only Matrix
          - type: macos
            runs-on: macos-15
            xcode: "/Applications/Xcode_16.4.app"
            use-xcbeautify: "true"
            build-only: "true"

          # iOS Build Matrix
          - type: ios
            runs-on: macos-14
            xcode: "/Applications/Xcode_15.1.app"
            deviceName: "iPhone 15"
            osVersion: "17.5"

          - type: ios
            runs-on: macos-15
            xcode: "/Applications/Xcode_16.4.app"
            deviceName: "iPhone 16 Pro"
            osVersion: "18.5"
            use-xcbeautify: "true"

          - type: ios
            runs-on: macos-15
            xcode: "/Applications/Xcode_26.0.app"
            deviceName: "iPhone 17 Pro"
            osVersion: "26.0"
            download-platform: "true"
            use-xcbeautify: "true"
            xcbeautify-renderer: "azure-devops-pipelines"

          - type: watchos
            runs-on: macos-15
            xcode: "/Applications/Xcode_16.4.app"
            deviceName: "Apple Watch Ultra 2 (49mm)"
            osVersion: "11.5"

          - type: watchos
            runs-on: macos-15
            xcode: "/Applications/Xcode_26.0.app"
            deviceName: "Apple Watch Ultra 3 (49mm)"
            osVersion: "26.0"
            download-platform: "true"
            use-xcbeautify: "true"
            xcbeautify-renderer: "github-actions"

          - type: visionos
            runs-on: macos-15
            xcode: "/Applications/Xcode_16.4.app"
            deviceName: "Apple Vision Pro"
            osVersion: "2.5"

          - type: tvos
            runs-on: macos-15
            xcode: "/Applications/Xcode_16.4.app"
            deviceName: "Apple TV 4K (3rd generation)"
            osVersion: "18.5"

          - type: tvos
            runs-on: macos-15
            xcode: "/Applications/Xcode_26.0.app"
            deviceName: "Apple TV 4K (3rd generation)"
            osVersion: "26.0"
            download-platform: "true"
            use-xcbeautify: "true"
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          working-directory: test/SingleTargetPackage
          scheme: SingleTargetPackage
          type: ${{ matrix.type }}
          xcode: ${{ matrix.xcode }}
          deviceName: ${{ matrix.deviceName }}
          osVersion: ${{ matrix.osVersion }}
          download-platform: ${{ matrix['download-platform'] || 'false' }}
          use-xcbeautify: ${{ matrix['use-xcbeautify'] }}
          xcbeautify-renderer: ${{ matrix['xcbeautify-renderer'] }}
          build-only: ${{ matrix['build-only'] || 'false' }}

  test-multi-target-macos:
    name: Test Multi-Target Package (macOS)
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        include:
          # SPM Build Matrix
          - runs-on: macos-15
            xcode: "/Applications/Xcode_16.4.app"
            use-xcbeautify: "true"
            xcbeautify-renderer: "github-actions"

          # SPM Build-Only Matrix
          - runs-on: macos-15
            xcode: "/Applications/Xcode_16.4.app"
            use-xcbeautify: "true"
            build-only: "true"

          # macOS Build Matrix
          - type: macos
            runs-on: macos-15
            xcode: "/Applications/Xcode_16.4.app"
            use-xcbeautify: "true"  

          # iOS Build Matrix
          - type: ios
            runs-on: macos-15
            xcode: "/Applications/Xcode_16.4.app"
            deviceName: "iPhone 16 Pro"
            osVersion: "18.5"
            use-xcbeautify: "true" 
            xcbeautify-renderer: "github-actions"

          - type: ios
            runs-on: macos-15
            xcode: "/Applications/Xcode_26.0.app"
            deviceName: "iPhone 16 Pro"
            osVersion: "18.5"
            download-platform: "true"
            use-xcbeautify: "true" 
            xcbeautify-renderer: "azure-devops-pipelines"

          - type: watchos
            runs-on: macos-15
            xcode: "/Applications/Xcode_16.4.app"
            deviceName: "Apple Watch Ultra 2 (49mm)"
            osVersion: "11.5"

          - type: watchos
            runs-on: macos-15
            xcode: "/Applications/Xcode_26.0.app"
            deviceName: "Apple Watch Ultra 2 (49mm)"
            osVersion: "11.5"
            download-platform: "true"
            use-xcbeautify: "true" 
            xcbeautify-renderer: "github-actions"

          - type: visionos
            runs-on: macos-15
            xcode: "/Applications/Xcode_16.4.app"
            deviceName: "Apple Vision Pro"
            osVersion: "2.5"

          - type: tvos
            runs-on: macos-15
            xcode: "/Applications/Xcode_16.4.app"
            deviceName: "Apple TV 4K (3rd generation)"
            osVersion: "18.5"

          - type: tvos
            runs-on: macos-15
            xcode: "/Applications/Xcode_26.0.app"
            deviceName: "Apple TV 4K (3rd generation)"
            osVersion: "26.0"
            download-platform: "true"
            use-xcbeautify: "true" 
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          working-directory: test/MultiTargetPackage
          scheme: MultiTargetPackage-Package
          type: ${{ matrix.type }}
          xcode: ${{ matrix.xcode }}
          deviceName: ${{ matrix.deviceName }}
          osVersion: ${{ matrix.osVersion }}
          download-platform: ${{ matrix['download-platform'] || 'false' }}
          use-xcbeautify: ${{ matrix['use-xcbeautify'] }}
          xcbeautify-renderer: ${{ matrix['xcbeautify-renderer'] }}
          build-only: ${{ matrix['build-only'] || 'false' }}

  test-single-target-ubuntu:
    name: Test Single Target Package (Ubuntu)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        swift:
          - "5.9"
          - "5.10"
          - "6.0"
          - "6.1"
          - "6.2"
        ubuntu:
          - jammy
          - focal
          - noble
        nightly:
          - false
          - true
        build-only:
          - false
          - true
        exclude:
          - swift: 5.9
            ubuntu: noble
          - swift: 5.9
            nightly: true
          - swift: 5.10
            nightly: true
          - swift: 6.0
            nightly: true
          - swift: 6.2
            nightly: false
          # Only test build-only for one swift version per ubuntu to reduce test matrix
          - swift: 5.9
            build-only: true
          - swift: 5.10
            build-only: true
          - swift: 6.0
            build-only: true
          - swift: 6.2
            build-only: true
    container:
      image: ${{ matrix.nightly && format('swiftlang/swift:nightly-{0}-{1}', matrix.swift, matrix.ubuntu) || format('swift:{0}-{1}', matrix.swift, matrix.ubuntu) }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          working-directory: test/SingleTargetPackage
          scheme: SingleTargetPackage
          use-xcbeautify: "true"
          build-only: ${{ matrix.build-only && 'true' || 'false' }} 

  test-multi-target-ubuntu:
    name: Test Multi-Target Package (Ubuntu)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        swift:
          - "5.9"
          - "5.10"
          - "6.0"
          - "6.1"
          - "6.2"
        ubuntu:
          - jammy
          - focal
          - noble
        nightly:
          - false
          - true
        build-only:
          - false
          - true
        exclude:
          - swift: 5.9
            ubuntu: noble
          - swift: 5.9
            nightly: true
          - swift: 5.10
            nightly: true
          - swift: 6.0
            nightly: true
          - swift: 6.2
            nightly: false
          # Only test build-only for one swift version per ubuntu to reduce test matrix
          - swift: 5.9
            build-only: true
          - swift: 5.10
            build-only: true
          - swift: 6.0
            build-only: true
          - swift: 6.2
            build-only: true
    container:
      image: ${{ matrix.nightly && format('swiftlang/swift:nightly-{0}-{1}', matrix.swift, matrix.ubuntu) || format('swift:{0}-{1}', matrix.swift, matrix.ubuntu) }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          working-directory: test/MultiTargetPackage
          scheme: MultiTargetPackage
          xcbeautify-renderer: "github-actions"
          build-only: ${{ matrix.build-only && 'true' || 'false' }}
  test-single-target-windows:
    name: Test Single Target Package (Windows)
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        runs-on: [windows-2022, windows-2025]
        build-only: [false, true]
        include:
          - swift-version: swift-6.2-branch
            swift-build: 6.2-DEVELOPMENT-SNAPSHOT-2025-09-06-a
          - swift-version: swift-6.1-release
            swift-build: 6.1-RELEASE
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          working-directory: test/SingleTargetPackage
          scheme: SingleTargetPackage
          windows-swift-version: ${{ matrix.swift-version }}
          windows-swift-build: ${{ matrix.swift-build }}
          use-xcbeautify: "true"
          build-only: ${{ matrix.build-only && 'true' || 'false' }} 

  test-multi-target-windows:
    name: Test Multi-Target Package (Windows)
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        runs-on: [windows-2022, windows-2025]
        build-only: [false, true]
        include:
          - swift-version: swift-6.2-branch
            swift-build: 6.2-DEVELOPMENT-SNAPSHOT-2025-09-06-a
          - swift-version: swift-6.1-release
            swift-build: 6.1-RELEASE
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          working-directory: test/MultiTargetPackage
          scheme: MultiTargetPackage-Package
          windows-swift-version: ${{ matrix.swift-version }}
          windows-swift-build: ${{ matrix.swift-build }}
          use-xcbeautify: "true"
          build-only: ${{ matrix.build-only && 'true' || 'false' }} 
