name: Swift Package Tests

on:
  push

jobs:
  test-single-target-macos:
    name: Test Single Target Package (macOS)
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        include:
          # SPM Build Matrix
          - runs-on: macos-15
            xcode: "/Applications/Xcode_16.4.app"

          # macOS Build Matrix
          - type: macos
            runs-on: macos-15
            xcode: "/Applications/Xcode_16.4.app"
            
          # iOS Build Matrix
          - type: ios
            runs-on: macos-14
            xcode: "/Applications/Xcode_15.1.app"
            deviceName: "iPhone 15"
            osVersion: "17.5"

          - type: ios
            runs-on: macos-15
            xcode: "/Applications/Xcode_16.4.app"
            deviceName: "iPhone 16 Pro"
            osVersion: "18.5"

          - type: ios
            runs-on: macos-15
            xcode: "/Applications/Xcode_26.app"
            deviceName: "iPhone 16 Pro"
            osVersion: "26.0"
            download-platform: "true"
  
          - type: watchos
            runs-on: macos-15
            xcode: "/Applications/Xcode_16.4.app"
            deviceName: "Apple Watch Ultra 2 (49mm)"
            osVersion: "11.5"

          - type: watchos
            runs-on: macos-15
            xcode: "/Applications/Xcode_26.app"
            deviceName: "Apple Watch Ultra 2 (49mm)"
            osVersion: "26.0"
            download-platform: "true"

          - type: visionos
            runs-on: macos-15
            xcode: "/Applications/Xcode_16.4.app"
            deviceName: "Apple Vision Pro"
            osVersion: "2.5"

          - type: tvos
            runs-on: macos-15
            xcode: "/Applications/Xcode_16.4.app"
            deviceName: "Apple TV 4K (3rd generation)"
            osVersion: "18.5"

          - type: tvos
            runs-on: macos-15
            xcode: "/Applications/Xcode_26.app"
            deviceName: "Apple TV 4K (3rd generation)"
            osVersion: "26.0"
            download-platform: "true"
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          working-directory: test/SingleTargetPackage
          scheme: SingleTargetPackage          
          type: ${{ matrix.type }}
          xcode: ${{ matrix.xcode }}
          deviceName: ${{ matrix.deviceName }}
          osVersion: ${{ matrix.osVersion }}
          download-platform: ${{ matrix.download-platform || 'false' }}

  test-multi-target-macos:
    name: Test Multi-Target Package (macOS)
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        include:
          # SPM Build Matrix
          - runs-on: macos-15
            xcode: "/Applications/Xcode_16.4.app"

          # macOS Build Matrix
          - type: macos
            runs-on: macos-15
            xcode: "/Applications/Xcode_16.4.app"
          
          # iOS Build Matrix
          - type: ios
            runs-on: macos-15
            xcode: "/Applications/Xcode_16.4.app"
            deviceName: "iPhone 16 Pro"
            osVersion: "18.5"

          - type: ios
            runs-on: macos-15
            xcode: "/Applications/Xcode_26.app"
            deviceName: "iPhone 16 Pro"
            osVersion: "18.5"
            download-platform: "true"
  
          - type: watchos
            runs-on: macos-15
            xcode: "/Applications/Xcode_16.4.app"
            deviceName: "Apple Watch Ultra 2 (49mm)"
            osVersion: "11.5"

          - type: watchos
            runs-on: macos-15
            xcode: "/Applications/Xcode_26.app"
            deviceName: "Apple Watch Ultra 2 (49mm)"
            osVersion: "11.5"
            download-platform: "true"

          - type: visionos
            runs-on: macos-15
            xcode: "/Applications/Xcode_16.4.app"
            deviceName: "Apple Vision Pro"
            osVersion: "2.5"

          - type: tvos
            runs-on: macos-15
            xcode: "/Applications/Xcode_16.4.app"
            deviceName: "Apple TV 4K (3rd generation)"
            osVersion: "18.5"

          - type: tvos
            runs-on: macos-15
            xcode: "/Applications/Xcode_26.app"
            deviceName: "Apple TV 4K (3rd generation)"
            osVersion: "26.0"
            download-platform: "true"
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          working-directory: test/MultiTargetPackage
          scheme: MultiTargetPackage-Package
          type: ${{ matrix.type }}
          xcode: ${{ matrix.xcode }}
          deviceName: ${{ matrix.deviceName }}
          osVersion: ${{ matrix.osVersion }}
          download-platform: ${{ matrix.download-platform || 'false' }}

  test-single-target-ubuntu:
    name: Test Single Target Package (Ubuntu)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        swift:
          - "5.9"
          - "5.10"
          - "6.0"
          - "6.1"
          - "6.2"
        ubuntu:
          - jammy
          - focal
          - noble
        nightly:
          - false
          - true
        exclude:
          - swift: 5.9
            ubuntu: noble
          - swift: 5.9
            nightly: true
          - swift: 5.10
            nightly: true
          - swift: 6.0
            nightly: true
          - swift: 6.2
            nightly: false
    container:
      image: ${{ matrix.nightly && format('swiftlang/swift:nightly-{0}-{1}', matrix.swift, matrix.ubuntu) || format('swift:{0}-{1}', matrix.swift, matrix.ubuntu) }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          working-directory: test/SingleTargetPackage
          scheme: SingleTargetPackage

  test-multi-target-ubuntu:
    name: Test Multi-Target Package (Ubuntu)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        swift:
          - "5.9"
          - "5.10"
          - "6.0"
          - "6.1"
          - "6.2"
        ubuntu:
          - jammy
          - focal
          - noble
        nightly:
          - false
          - true
        exclude:
          - swift: 5.9
            ubuntu: noble
          - swift: 5.9
            nightly: true
          - swift: 5.10
            nightly: true
          - swift: 6.0
            nightly: true
          - swift: 6.2
            nightly: false
    container:
      image: ${{ matrix.nightly && format('swiftlang/swift:nightly-{0}-{1}', matrix.swift, matrix.ubuntu) || format('swift:{0}-{1}', matrix.swift, matrix.ubuntu) }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          working-directory: test/MultiTargetPackage
          scheme: MultiTargetPackage 
